[build]
  base = "frontend"
  publish = "build"
  command = "npm run build"

[[redirects]]
  from = "/api/*"
  to = "https://us-app-backend.herokuapp.com/api/:splat" # Placeholder, user needs to change this
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
